apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-sentiment
  namespace: kubeflow-user-example-com
spec:
  name: seldon-sentiment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldon-sentiment:0.1
          name: classifier
    graph:
      children: []
      endpoint:
        type: REST
      name: sentiment
      type: MODEL
    name: example
    replicas: 1
